version: '3'

services:
  postgres:
    image: postgres:12.6
    environment:
      POSTGRES_PASSWORD: "uf48c.3du.8r"
      POSTGRES_USER: "ufabc"
      POSTGRES_DB: "refeicao_bd"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "william.sena@ufabc.edu.br"
      PGADMIN_DEFAULT_PASSWORD: "uf48c.3du.8r"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - postgres-network  

networks: 
  postgres-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local